import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/lib/provider";
import { fontMapper } from "@/font";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(fontMapper["font-gt-alsheim-pro"])}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
